version: '3.9'
    #PHP 8.0.11 - Nginx
services:
    #PHP Service
    php_8_0_11:
        # image: php:8.0.11-fpm-alpine3.14
        build: ./
        container_name: php_8_0_11
        tty: true
        working_dir: /var/www
        volumes: 
            - ./app/public/:/var/www
        networks: 
            - local-bridge

    #Nginx Service
    nginx: 
        image: nginx:alpine
        container_name: nginx
        tty: true
        volumes: 
            - ./app/public/:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        ports: 
            - 80:80
        networks: 
            - local-bridge

    # mysql:8.0.26
    mysql: 
        image: mysql:8.0.26
        container_name: mysql
        restart: always
        environment: 
            MYSQL_DATABASE: testdb
            MYSQL_ROOT_PASSWORD: mypassword
            MYSQL_USER: user
            MYSQL_PASSWORD: mypassword
        ports: 
            - 3306:3306
        networks: 
            - local-bridge
    
    #phpmyadmin
    phpmyadmin:
        image: phpmyadmin
        restart: always
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_USER: user
            PMA_PASSWORD: mypassword
            MYSQL_ROOT_PASSWORD: mypassword
        depends_on:
            - mysql
        ports: 
            - 8080:80
        networks: 
            - local-bridge
    #composer
    composer:
        image: composer:latest
        container_name: composer
        tty: true
        command: ['composer','install']
        volumes:
            - ./app/public/:/app
    
#network
networks:
    local-bridge:
        driver: bridge
